import {LOW_STOCK_THRESHOLD} from './config';

export const LOW_STOCK_PERCENT = 0.3;

export const getStockSeverity = (stock, capacity, threshold = LOW_STOCK_THRESHOLD) => {
  if (stock <= 0) {
    return 'critical';
  }

  const percent = capacity > 0 ? stock / capacity : 1;
  if (stock <= threshold || percent <= LOW_STOCK_PERCENT) {
    return 'warning';
  }

  return null;
};

const timestamp = () => new Date().toISOString().slice(0, 16).replace('T', ' ');

export const buildLowStockAlert = ({
  id,
  deviceId,
  deviceName,
  productName,
  productId,
  stock,
  capacity,
  severity,
}) => ({
  id,
  type: 'Low Stock',
  autoGenerated: true,
  deviceId,
  deviceName,
  productName,
  productId,
  stock,
  capacity,
  severity,
  issue:
    severity === 'critical'
      ? `Out of Stock: ${productName}`
      : `Low Stock: ${productName} (${stock} left)`,
  time: timestamp(),
  resolved: false,
});

export const buildLowStockAlertsFromDevices = (devices, threshold = LOW_STOCK_THRESHOLD) => {
  const alerts = [];

  devices.forEach(device => {
    (device.layers ?? []).forEach(layer => {
      (layer.slots ?? []).forEach(slot => {
        if (!slot.product) {
          return;
        }

        const stock = slot.current ?? 0;
        const capacity = slot.capacity ?? 0;
        const severity = getStockSeverity(stock, capacity, threshold);
        if (!severity) {
          return;
        }

        const productKey = slot.product.replace(/\s+/g, '-').toLowerCase();
        alerts.push(
          buildLowStockAlert({
            id: `lowstock-${device.id}-${layer.id}-${slot.slot}-${productKey}`,
            deviceId: device.id,
            deviceName: device.name,
            productName: slot.product,
            productId: slot.productId,
            stock,
            capacity,
            severity,
          }),
        );
      });
    });
  });

  return alerts;
};

export const summarizeLowStock = (alerts = []) => {
  const lowStock = alerts.filter(alert => !alert.resolved && alert.type === 'Low Stock');
  const critical = lowStock.filter(alert => alert.severity === 'critical');
  const warning = lowStock.filter(alert => alert.severity === 'warning');
  const deviceIds = new Set(lowStock.map(alert => alert.deviceId));

  return {
    total: lowStock.length,
    criticalCount: critical.length,
    warningCount: warning.length,
    deviceCount: deviceIds.size,
    alerts: lowStock,
    critical,
    warning,
  };
};

export const buildRestockSuggestions = (alerts = [], devices = []) => {
  const summary = summarizeLowStock(alerts);
  const deviceById = devices.reduce((acc, device) => {
    acc[device.id] = device;
    return acc;
  }, {});

  const grouped = new Map();

  summary.alerts.forEach(alert => {
    if (!grouped.has(alert.deviceId)) {
      grouped.set(alert.deviceId, {
        device: deviceById[alert.deviceId] ?? {
          id: alert.deviceId,
          name: alert.deviceName,
        },
        items: [],
        criticalCount: 0,
        warningCount: 0,
      });
    }

    const entry = grouped.get(alert.deviceId);
    entry.items.push(alert);
    if (alert.severity === 'critical') {
      entry.criticalCount += 1;
    } else {
      entry.warningCount += 1;
    }
  });

  return Array.from(grouped.values()).sort((a, b) => {
    if (b.criticalCount !== a.criticalCount) {
      return b.criticalCount - a.criticalCount;
    }
    return b.items.length - a.items.length;
  });
};

// Consolidates restock suggestions across every machine that needs a visit
// into a single "what to bring" list — quantity per product needed to top
// every low/out-of-stock slot back up to capacity.
export const buildPackingList = (restockSuggestions = []) => {
  const byProduct = new Map();

  restockSuggestions.forEach(suggestion => {
    suggestion.items.forEach(item => {
      if (!item.productName) {
        return;
      }
      const qty = Math.max((item.capacity || 0) - (item.stock || 0), 1);
      const entry = byProduct.get(item.productName) || {
        productName: item.productName,
        qty: 0,
        deviceCount: 0,
      };
      entry.qty += qty;
      entry.deviceCount += 1;
      byProduct.set(item.productName, entry);
    });
  });

  return Array.from(byProduct.values()).sort((a, b) => b.qty - a.qty);
};

// Planogram cells on some accounts carry no stock numbers or images, but the
// inventory endpoint reports each product's stock per machine. Fill slot gaps
// from inventory; when a product occupies several slots, split its machine
// stock evenly across them.
export const enrichLayersWithInventory = (layers, inventoryProducts, deviceId) => {
  if (!layers?.length || !inventoryProducts?.length) {
    return layers ?? [];
  }

  const byId = new Map();
  const byName = new Map();
  inventoryProducts.forEach(product => {
    if (product.id != null) {
      byId.set(product.id, product);
    }
    if (product.name) {
      byName.set(product.name, product);
    }
  });

  const slotCounts = new Map();
  layers.forEach(layer =>
    (layer.slots ?? []).forEach(slot => {
      const key = slot.productId ?? slot.product;
      if (key) {
        slotCounts.set(key, (slotCounts.get(key) || 0) + 1);
      }
    }),
  );

  const assignedSlots = new Map();

  return layers.map(layer => ({
    ...layer,
    slots: (layer.slots ?? []).map(slot => {
      const needsStock = !(slot.capacity > 0) && !(slot.current > 0);
      const needsImage = !slot.image;
      if (!needsStock && !needsImage) {
        return slot;
      }

      const inventory =
        (slot.productId != null && byId.get(slot.productId)) ||
        byName.get(slot.product);
      if (!inventory) {
        return slot;
      }

      const next = {...slot};
      if (needsImage && inventory.image) {
        next.image = inventory.image;
      }

      if (needsStock) {
        const market = inventory.markets?.find(m => m.marketId === deviceId);
        if (market) {
          const key = slot.productId ?? slot.product;
          const count = slotCounts.get(key) || 1;
          const index = assignedSlots.get(key) || 0;
          const total = market.stock ?? 0;
          next.current = Math.floor(total / count) + (index < total % count ? 1 : 0);
          assignedSlots.set(key, index + 1);
          if (market.capacity > 0) {
            next.capacity = market.capacity;
          }
        }
      }

      return next;
    }),
  }));
};
